# Generated by Django 4.1.1 on 2022-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0066_systemuser_job_sent_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_sent_list',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
